trainer:
  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      api_key: 'api_key'
      workspace: 'workspace'
      project_name: 'project_name'
      save_dir: 'logs'
  max_epochs: 30
model:
    num_classes: 10
    criterion:
      class_path: torch.nn.CrossEntropyLoss
      init_args:
        reduction: mean
data:
  data_dir: 'Datasets/Dataset'
  batch_size: 64
  num_workers: 4
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 4
early_stopping:
  monitor: "Val Loss"
  patience: 5
