quick_settings:
  do_model: True
  do_dataset: False
  do_database: False
  dataset_name: &ds "Dataset"
  database_name: &db "Database"

model:
  init_parameters:
    device: "cuda"
    dataset_name: *ds

  pretrained_parameters:
    model_name: "resnet50"
    weights_file_name: null

  model_parameters:
    criterion: "CrossEntropyLoss"
    optimizer: "Adam"
    scheduler:
      sched_name: "StepLR"
      params:
        step_size: 4
        gamma: 0.1

  train_parameters:
    num_epochs: 20
    batch_size: 128
    use_weighted_sampler: True
    weights_file_name: null

dataset:
  init_parameters:
    database_name: *db
    dataset_name: *ds

  creation_parameters:
    fixed_split: 40
    oversample: False
    create_csv: True

database:
  init_parameters:
    csv_file: "spiders.csv"
    database_name: *db
    imgs_threshold: 100

  creation_parameters:
    save_images: True
    with_license: True
    check_images: True
    print_info: True
    database_csv_name: "database.csv"
    plot_name: "distribution.png"
